
name: 'Bump version'
on:
    push:
        branches:
            - stable

jobs:
    bump:
        name: Bump the version
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 2
                    ref: stable
            -   run: .github/actions/version-bumping/bumpversion.sh
                id: bumping
            -   uses: actions/create-release@v1
                id: create_release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: "v${{ steps.bumping.outputs.version }}"
                    release_name: "Version ${{ steps.bumping.outputs.version }}"
                    draft: false
            -   uses: actions/upload-release-asset@v1.0.2
                id: upload_asset
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: "${{ steps.create_release.outputs.upload_url }}"
                    asset_path: ./archive.tar.gz
                    asset_name: Archive.tar.gz
                    asset_content_type: application/gzip
            #-   run: echo "Download URL: ${{ steps.upload_asset.outputs.browser_download_url }}"
