
name: 'Bump version'
on:
    push:
        branches:
            - stable

jobs:
    bump:
        name: Bump the version
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 2
                    ref: stable
            -   run: .github/actions/version-bumping/bumpversion.sh
